### ISSUE TITLE
Add a way to toggle menu when on smartphone

### ISSUE THREAD

**Issue by jvoisin** [radareorg/radareorg#30]
@pancake requested that the menu must be hidden by default on smartphone, with a button to toggle it. I don't plan to invest time to implement this in the near future (mostly because I don't currently have the patience to play with css, responsivity and javascript), feel free to take the issue.

**Comment by joenano** [comment]
I could do this.

**Comment by jvoisin** [comment]
Be my guest ♥

**Comment by jvoisin** [comment]
Closed by #39 ♥
