### ISSUE TITLE
Feedbacks compilation

### ISSUE THREAD

**Issue by afiskon** [radareorg/radareorg#54]
For some reason people were asking me to leave comments here on GitHub, not in Telegram, thus I created this thread. If anyone would like to share their feedback I suggest to do it here as well.

(1/2)  Current site IMHO looks better - design, colors and stuff. I like the idea "if you see an issue fix it on github" of beta though. It will serve well in the long run.

(2/2) I checked the mobile version, it's OK. On second thought the design is not that bad, also I'm not a web designer. Broken HTTPS is the most critical issue. TL;DR beta is generally fine and anyway you can improve it with time. Personally I would configure Let's Encrypt and replace the web site.

**Comment by rfc2119** [comment]
Overall, no complaints. The page [talks](http://radare2s-website.readthedocs.io/en/latest/talks.html#talks) however, is not accessible directly (you need to go to "documentation", then [contributions](http://radare2s-website.readthedocs.io/en/latest/documentation.html#contributions) and click on "talking about"). I suggest we put it on a separate tab or make it more visible. This would ease the process of learning r2 for newcomers.

**Comment by Maijin** [comment]
Feedback from @enovella (Telegram)
"Very readable"

**Comment by zxgio** [comment]
Under "download/download binaries" in Linux there is a link to github, instead of http://radare.mikelloc.com/get/2.5.0/ (where deb packages can be found)

**Comment by jvoisin** [comment]
done in ab0aa90f69c7bc63b5b3056887953745e9ab3ccf
