### ISSUE TITLE
Feedback: Good content, Bad design

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/radareorg#56]
Well, it is very intuitive and pretty informative and I do believe that simplify the current website as well as give it a fresh new look is an awesome idea.

However, I do believe that a website is the presenter of the project. Means, that it shouldn't be **just** informative but also to look good.
IMHO, a more modern design will do good for r2's pr and be more user-friendly. So without going round and round, I don't feel like this one looks pretty. It gives me the feeling of an old non-modern platform.

Should it look pretty at all? Well, I believe **yes**. As well as _responsive_, _informative_, _intuitive_ and all the good things that currently present on the beta website.

I think @jvoisin did an awesome work content-wise. But still, don't think it's beautiful in any way. The current website isn't the most handsome prince in the kingdom, but it's better IMO.

Just for an example, x64dbg have done a really nice work with the design of theirs, it is very welcoming (although has problems of its own):
Main website: https://x64dbg.com
Blog: https://x64dbg.com/blog/

**Comment by radare** [comment]
Totally agree

**Comment by Maijin** [comment]
x64dbg website is just a single page with a scroll it's totally not comparable with what @jvoisin did and the current requirements that were expressed already :S

**Comment by Maijin** [comment]
or we have this single scrolling page and the menu point to the read docs thing

**Comment by ITAYC0HEN** [comment]
yeah, absolutely. one page isn't what we are talking about. And I hate this "click to scroll" thing that hooks your keyboard and makes your life awful.
But, the design is modern, welcoming, good reception experience for newcomers and that what I wanted to emphasize here.
Fonts, colors, pictures etc

**Comment by Maijin** [comment]
ok that I agree with too

**Comment by xarkes** [comment]
Other source of inspiration:
https://google.github.io/xi-editor/index.html
I think their website is clean and efficient.
Sober first page, and complete documentation.

**Comment by jvoisin** [comment]
There is nothing actionable in this issue, and I'm not a web designer. Anybody is free to send a pull-request to improve the [css]( https://github.com/radareorg/radareorg/blob/master/source/_static/css/custom.css ) :)
