### ISSUE TITLE
Force a fixed height for the travis button

### ISSUE THREAD

**Issue by radare** [radareorg/radareorg#8]

**Comment by jvoisin** [comment]
The button already has a fixed size.

**Comment by radare** [comment]
make it easy.

- [x] move the input search over the menu
- [x] remove the Go button
- [ ] put the travis button UNDER the menu

**Comment by jvoisin** [comment]
I won't remove the go button because accessibility matters.

**Comment by jvoisin** [comment]
To move the travis button, I need to modify the theme, E_TOOLAZY for now.

**Comment by jvoisin** [comment]
Done in 9352db9f4fb60f3038cbc3e9d4f8d2e6c0e513f3
